name: Build Bazzite KDE Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Buildah
        uses: redhat-actions/setup-buildah@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Bazzite KDE image
        uses: redhat-actions/buildah-build@v2
        id: build_image
        with:
          containerfiles: |
            ./Containerfile
          image: ghcr.io/${{ github.repository_owner }}/bazzite-kde
          tags: latest
          context: .
          format: docker
          labels: |
            containers.bootc=1
            org.opencontainers.image.title=Bazzite-KDE
            org.opencontainers.image.description=Customized Bazzite KDE Fedora image
            org.opencontainers.image.version=latest
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.licenses=Apache-2.0

      - name: Push image to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        # The 'if' condition is simplified to just check the branch.
        # The login action itself will handle missing secrets.
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        # Same as above, the 'if' condition is simplified.
        if: github.ref == 'refs/heads/main'
        run: |
          buildah push ${{ steps.build_image.outputs.image }}:${{ steps.build_image.outputs.tags }} docker://docker.io/${{ secrets.DOCKERHUB_USERNAME }}/bazzite-kde:${{ steps.build_image.outputs.tags }}
